config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users,
             controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      patch 'vote_reset'
    end
  end

  concern :commentable do
    member do
      post 'add_comment'
    end
  end

  resources :questions, concerns: %i[votable commentable], shallow: true do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch 'favorite', on: :member
    end
    resources :subscriptions, only: %i[create destroy]
  end

  resources :attachments, only: :destroy

  resources :rewards, only: %i[index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_one :reward, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  after_create { subscribe(user) }

  scope :daily, -> { where(created_at: 1.day.ago.midnight..Time.now.midnight) }

  def subscribe(user)
    subscriptions.create(user: user)
  end

  def unsubscribe(user)
    subscriptions.find_by(user: user).destroy
  end

  def subscription_of(user)
    subscriptions.find_by(user_id: user&.id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  load_and_authorize_resource

  def index
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      render json: @question, status: :created, location: @question
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question, status: :ok, location: @question
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy!

    head :no_content
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                     links_attributes: %i[id name url _destroy],
                                     reward_attributes: %i[id title image _destroy])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show update destroy]
  after_action :publish_question, only: %i[create]

  respond_to :js

  load_and_authorize_resource

  skip_authorization_check only: %i[index]

  include Voted
  include Commented

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    @answer = @question.answers.build
    @subscription = @question.subscription_of(current_user)
    gon.question_id = @question.id
    respond_with @question
  end

  def new
    @question = Question.new
    respond_with @question
  end

  def create
    @question = current_user.questions.create(question_params)
    respond_with @question
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with @question.destroy
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                     links_attributes: %i[id name url _destroy],
                                     reward_attributes: %i[id title image _destroy])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast('questions_channel',
                                 ApplicationController.render(partial: 'questions/question',
                                                              locals: { question: @question }))
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_edit_form.html.slim
= form_with model: @question, local: false, class: 'hidden', html: { id: "edit-question-#{@question.id}" } do |f|
  p
    = f.label :title, 'Question title'
    = f.text_area :title
  p
    = f.label :body, 'Question body'
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p 
    = f.fields_for :links do |l| 
      = render 'link_fields', f: l
    .links
      = link_to_add_association 'add link', f, :links
  p
    = f.submit 'Save'

app/views/questions/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
    
  = link_to_remove_association "remove link", f

app/views/questions/_question.html.slim
.question id="question-#{question.id}"   
  = link_to question_path(question), class: "list-group-item list-group-item-action"
    .question_title
      strong = question.title
    .question_body
      = question.body
hr

app/views/questions/_reward_fields.html.slim
.nested-fields
  .field
    = f.label :title, 'Reward title'
    = f.text_field :title
  .field
    = f.label :image, 'Reward image'
    = f.file_field :image, direct_upload: true

  = link_to_remove_association "remove", f

app/views/questions/index.html.slim
p "Questions list:"
- cache collection_cache_key_for :question do
  .list-group id="questions"
    = render @questions

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question
.row class="justify-content-center"
  .col-md-4 class="card card-border-primary"
    .card-body
      = form_with model: @question, local: true do |f|
        .form-group
          .form-floating
            = f.text_field :title, class: "form-control"
            = f.label :title, class: "form-label"
          .form-floating class="mt-2"
            = f.text_area :body, class: "form-control"
            = f.label :body, class: "form-label"
          p
            = f.label :files
            = f.file_field :files, multiple: true, direct_upload: true, class: "btn btn-outline-dark m-2"

          p Links:
          p
            = f.fields_for :links do |l|
            .links
              = link_to_add_association 'add link', f, :links, class: "btn btn-outline-dark"

          p Reward:
          p
            = f.fields_for :reward do |r|
            .reward
              = link_to_add_association 'create reward', f, :reward, class: "btn btn-outline-dark"

          p
            = f.submit 'Ask', class: "btn btn-outline-dark"

app/views/questions/show.html.slim
.question-errors
  = render 'shared/errors', resource: @question

.question class="card container-fluid" data={ question_id: @question.id }
  - cache @question do
    .card-header class="col" id="question-title"
      .row class="align-self-start"
        = @question.title

      .row
        .col class="align-self-end"
          . id="question-#{@question.id}-rating"
            | question rate:
            = @question.rating
        .col-auto class="align-self-end"
          = render 'shared/votes', resource: @question

    .card-body id="question-body"
      | Question:
      = @question.body


  = render 'shared/subscription', resource: @question

  .card class="m-2"
    = render 'shared/comments', resource: @question

  p | reward:
  . id="question-reward"
    - if @question.reward
      - cache @question.reward do
        = @question.reward.title
        = image_tag @question.reward.image, style: "width: 100px"

  . id="question-files"
    - if @question.files.attached?
      = render 'shared/files', resource: @question

  . id="question-links"
    = render 'shared/links', resource: @question


  - if can?(:modify, @question)
    .question_buttons class="mt-2"
      = link_to 'Edit question', '#', class: 'edit-question-link btn btn-outline-dark m-2', data: { question_id: @question.id }
      = link_to 'Delete question', question_path(@question), class: "btn btn-outline-dark", method: :delete, data: { confirm: "Are you sure?" }
  = render 'edit_form'


p | Answers:

.answers id="answers"
  = render @question.answers

- if user_signed_in?
  = render 'answers/form'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% unless @question.errors.present? %>
  $('#question-title').html('<%= j @question.title %>');
  $('#question-body').html('Question: <%= j @question.body %>');
  $('#question-files').html('<%= render 'shared/files', resource: @question %>');
  $('#question-links').html('<%= render 'shared/links', resource: @question %>');
<% end %>