config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users,
             controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      patch 'vote_reset'
    end
  end

  concern :commentable do
    member do
      post 'add_comment'
    end
  end

  resources :questions, concerns: %i[votable commentable], shallow: true do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch 'favorite', on: :member
    end
    resources :subscriptions, only: %i[create destroy]
  end

  resources :attachments, only: :destroy

  resources :rewards, only: %i[index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/shared/_comment_form.slim
= form_with model:resource.comments, url: polymorphic_path(resource, action: 'add_comment'), local: false, class: 'hidden comment_submit m-2', html: { id: "comment-#{resource.class.name.downcase}-#{resource.id}" } do |f|
  .form-group
    = f.label :body, 'Comment body', class: "form-label text-muted"
    = f.text_area :body, class: "form-control"

  p
    = f.submit 'Add', class: "btn btn-outline-dark m-2"

app/views/shared/_comments.slim
. id="#{resource.class.name.downcase}-#{resource.id}-comments"

  p Comments:

  . id="comment-errors"

  - resource.comments&.each do |comment|
    - cache comment do
      .comment class="card m-2 text-muted" id="comment-#{comment.id}"
        = comment.body
- if can?(:add_comment, resource)
  = link_to 'Add comment', '#', class: 'add-comment-link', data: { resource_name: resource.class.name.downcase, resource_id: resource.id }
  = render 'shared/comment_form', resource: resource

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b = "#{resource.errors.count} error(s) detected: "
  ul
    - resource.errors.full_messages.each do |message|
      li class="alert alert-secondary"
        = message

app/views/shared/_files.html.slim
p Files:

- resource.files.each do |file|
  .file id="file-#{file.id}"
    = link_to file.filename.to_s, url_for(file)

    - if can?(:modify, resource)
      p
        = link_to "delete_file", attachment_path(file.id), method: :delete, remote: true, data: { confirm: 'Are you sure?' }

app/views/shared/_links.html.slim
p Links:

ul 
  - resource.links.each do |link|
    .link id="link-#{link.id}"
      - if link.gist?
        = link_to link.name, link.url

        code data-gist-id="#{link.gist_id}"
     
      - else
        li = link_to link.name, link.url

app/views/shared/_subscription.html.slim
- if can?(:create, Subscription) && !current_user.subscribed?(@question)
  = link_to 'Subscribe', question_subscriptions_path(@question), method: :post, remote: true
- if current_user&.subscribed?(@question) && can?(:destroy, @subscription)
  = link_to 'Unsubscribe', subscription_path(@subscription), method: :delete, remote: true

app/views/shared/_votes.html.slim
- if can?(:vote, resource)

  .row id="#{resource.class.name.downcase}-#{resource.id}-vote"
    . id="vote-errors"
    .col-auto
      p Vote:

    .col-auto
      . class=(current_user&.voted?(resource) ? 'hidden' : '') id="#{resource.class.name.downcase}-#{resource.id}-vote_up"
        = link_to 'Positive', polymorphic_path(resource, action: 'vote_up'), method: :post, remote: true, class: "vote", data: { type: :json }
      . class=(current_user&.voted?(resource) ? 'hidden' : '') id="#{resource.class.name.downcase}-#{resource.id}-vote_down"
        = link_to 'Negative', polymorphic_path(resource, action: 'vote_down'), method: :post, remote: true, class: "vote", data: { type: :json }

      . class=(!current_user&.voted?(resource) ? 'hidden' : '') id="#{resource.class.name.downcase}-#{resource.id}-reset_vote"
        = link_to 'Reset Vote', polymorphic_path(resource, action: 'vote_reset'), method: :patch, remote: true, class: "vote", data: { type: :json }