config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users,
             controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      patch 'vote_reset'
    end
  end

  concern :commentable do
    member do
      post 'add_comment'
    end
  end

  resources :questions, concerns: %i[votable commentable], shallow: true do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch 'favorite', on: :member
    end
    resources :subscriptions, only: %i[create destroy]
  end

  resources :attachments, only: :destroy

  resources :rewards, only: %i[index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :user
  belongs_to :question, touch: true

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  after_create_commit :broadcast_self, :notify

  def make_favorite!
    transaction do
      question.answers.update_all(favorite: false)
      update!(favorite: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def broadcast_self
    ActionCable.server.broadcast("questions_channel_#{question.id}",
                                 { answer: self,
                                   answer_rating: rating,
                                   answer_files: files_array,
                                   answer_links: links_array,
                                   question: question })
  end

  def files_array
    files.map do |file|
      { id: file.id,
        name: file.filename.to_s,
        url: Rails.application.routes.url_helpers.rails_blob_path(file, only_path: true) }
    end
  end

  def links_array
    links.map do |link|
      { id: link.id,
        name: link.name,
        url: link.url,
        gist: link.gist?,
        gist_id: link.gist_id }
    end
  end

  def notify
    NewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  before_action :find_answer, only: %i[update destroy favorite]
  before_action :find_question, only: %i[create]

  respond_to :js

  authorize_resource

  include Voted
  include Commented

  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = @question
    respond_with @answer.save
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
    respond_with @answer
  end

  def destroy
    respond_with @answer.destroy
  end

  def favorite
    respond_with @answer.make_favorite!
  end

  private

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def find_question
    @question = Question.with_attached_files.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[id name url _destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: %i[index create]
  load_and_authorize_resource class: "Answer"

  def index
    render json: @question.answers, each_serializer: AnswersSerializer
  end

  def show
    render json: @answer
  end

  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = @question
    if @answer.save
      render json: @answer, status: :created, location: @answer
    else
      render json: @answer.errors, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer, status: :ok, location: @answer
    else
      render json: @answer.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy!

    head :no_content
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [],
                                   links_attributes: %i[id name url _destroy])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?

  .answer class="card m-2 container-fluid" id="answer-#{answer.id}"
    . id="answer-errors-#{answer.id}"

    - cache answer do

      = answer.favorite? ? octicon('star-fill') : octicon('star')

      .card-body id="answer-body-#{answer.id}"
        = answer.body

    .card class="m-2"
      = render 'shared/comments', resource: answer


    - if can?(:favorite, answer) && !answer.favorite?
      p
        = link_to 'Favorite', favorite_answer_path(answer), class: 'favorite-answer-link', method: :patch, remote: true, data: { answer_id: answer.id }


    - if can?(:modify, answer)
      p
        = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      p
        = link_to 'Delete answer', answer_path(answer), class: 'delete-answer-link', method: :delete, remote: true, data: { answer_id: answer.id, confirm: "Are you sure?" }

    = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      .form-floating
        = f.text_area :body, class: "form-control"
        = f.label :body, 'Your answer', class: "form-label"

      p
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true, class: "btn btn-outline-dark"
      p
        = f.fields_for :links do |l|
          = render 'link_fields', f: l
        .links
          = link_to_add_association 'add link', f, :links, class: "btn btn-outline-dark"
      p
        = f.submit 'Save', class: "btn btn-outline-dark"
    .card-footer class="row"
      .col
        . id="answer-#{answer.id}-rating"
          | answer rate:
          = answer.rating
        = render 'shared/votes', resource: answer

      .col id="answer-#{answer.id}-links"
        = render 'shared/links', resource: answer

      .col id="answer-#{answer.id}-files"
        - if answer.files.attached?
          = render 'shared/files', resource: answer

app/views/answers/_form.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer

p | New answer:
= form_with model: [@question, @answer], local: false, class: "new-answer form-control" do |f|

  .form-floating
    = f.text_area :body, class: "form-control"
    = f.label :body, class: "form-label"

  .row class="align-items-center"
    .col-auto
      = f.label :files, class: "form-label"
      = f.file_field :files, multiple: true, direct_upload: true, class: "btn btn-outline-dark m-2"

    = f.fields_for :links do |l|
      = render 'link_fields', f: l
    .links class="col-auto"
      = link_to_add_association 'add link', f, :links, class: "btn btn-outline-dark m-2"

  p
    = f.submit 'Answer the question', class: "btn btn-outline-dark"

app/views/answers/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
    
  = link_to_remove_association "remove link", f

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

$("form.new-answer").trigger("reset");

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();

app/views/answers/update.js.erb
$('div#answer-errors-<%= @answer.id %>').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $('#answer-body-<%= @answer.id %>').html('<%= j @answer.body %>');
  $('#answer-<%= @answer.id %>-files').html('<%= render 'shared/files', resource: @answer %>');
  $('#answer-<%= @answer.id %>-links').html('<%= render 'shared/links', resource: @answer %>');
<% end %>