config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users,
             controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      patch 'vote_reset'
    end
  end

  concern :commentable do
    member do
      post 'add_comment'
    end
  end

  resources :questions, concerns: %i[votable commentable], shallow: true do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch 'favorite', on: :member
    end
    resources :subscriptions, only: %i[create destroy]
  end

  resources :attachments, only: :destroy

  resources :rewards, only: %i[index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Qna
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = Gon::Base.render_data
    = action_cable_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "application", 'data-turbolinks-track': "reload"
    = javascript_pack_tag "application", 'data-turbolinks-track': "reload"
  

  body
    .container-fluid
      . class="navbar navbar-expand-lg navbar-light bg-light"
        . class="container-fluid"
          . class="nav-item"
            = link_to 'Questions', questions_path, class: "nav-link active"
            - if can?(:create, Question)
              = link_to 'Ask question', new_question_path, class: "nav-link active"
            = current_user&.email
          . class="nav-item"  
            - if current_user
              = link_to 'Log out', destroy_user_session_path, class: "nav-link active", method: :delete
            - unless current_user
              . 
                = link_to "Log in", new_session_path(resource_name)
              .
                = link_to "Sign up", new_registration_path(resource_name)
                        
      p class="notice" = notice 
      p class="alert" = alert
      == yield